AHP2/AHP2/Models/PartialMenuViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AHP2.Models
{
    public enum MenuItem
    {
        Objective,
        Criterions,
        CriterionsRating,
        SubCriterions,
        SubCriterionsRating,
        Alternatives,
        AlternativesToCriterionsRating,
        AlternativesToSubCriterionsRating,
        Summary
    }

    public class PartialMenuViewModels
    {
        public MenuItem MenuItem { set; get; }  
        public int  ObjectRouting { set; get; }
        
        public PartialMenuViewModels()
        {

        }  

        public PartialMenuViewModels(MenuItem menuItem)
        {
            this.MenuItem = menuItem;
        }

        public string GetNameMenuItem(MenuItem menuItem)
        {
            switch(menuItem)
            {
                case MenuItem.Objective: return "Objective";
                case MenuItem.Criterions: return "Criteria";
                case MenuItem.CriterionsRating: return "Comparision of criteria";
                case MenuItem.SubCriterions: return "Sub-criteria";
                case MenuItem.SubCriterionsRating: return "Comparision of sub-criteria";
                case MenuItem.Alternatives: return "Alternatives";
                case MenuItem.AlternativesToCriterionsRating: return "Comparision of criteria - alternatives";
                case MenuItem.AlternativesToSubCriterionsRating: return "Comparision of sub-criteria - alternatives";
                case MenuItem.Summary: return "Summary";
                default: return "";
            }
        }

        public List<MenuItem> GetAllMenuItems
        {
            get
            {
                return Enum.GetValues(typeof(MenuItem)).Cast<MenuItem>().ToList();
            }
        }
    }
}

AHP2/AHP2/Controllers/PartialMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHP2.Controllers
{
    public class PartialMenuController : Controller
    {
        // GET: PartialMenu
        public ActionResult Diverter(string id)
        {
            var str = id.Split('-');

            switch(int.Parse(str[0].ToString()))
            {
                case 0: return RedirectToAction("Update", "Objective", new { id = str[1]});
                case 1: return RedirectToAction("Update", "Criterion");
                case 2: return RedirectToAction("UpdateRate", "Criterion");
                case 3: return RedirectToAction("Update", "SubCriterion");
                case 4: return RedirectToAction("UpdateRate", "SubCriterion");
                case 5: return RedirectToAction("Update", "Alternatives");
                case 6: return RedirectToAction("UpdateRateCriteria", "Alternatives");
                case 7: return RedirectToAction("UpdateRateSubCriteria", "Alternatives");
                case 8: return RedirectToAction("Show", "Summary");
                default:
                    return new ViewResult
                    {
                        ViewName = "~/Views/Errors/Error.cshtml",
                    };
            }
        }
    }
}

AHP2/AHP2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Session["User"] != null)
                    {

                        <li>@Html.ActionLink("Log out", "LogOut", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Log in", "LogIn", "User")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Simple AHP Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>

    </script>
</body>
</html>

AHP2/AHP2/Views/Shared/_PartialMenu.cshtml
@model AHP2.Models.PartialMenuViewModels

@{ 
    
}

<table class="table table-hover well well-sm">
    @foreach(var e in Model.GetAllMenuItems)
    {
        <tr>
            <td>
                @if(e == Model.MenuItem)
                {
                    @Html.ActionLink(@Model.GetNameMenuItem(e), "Diverter", "PartialMenu"
              , new { id = (int)e + "-" + Model.ObjectRouting}, htmlAttributes: new object { })
                }
                else
                {
                    @Html.ActionLink(@Model.GetNameMenuItem(e), "Diverter", "PartialMenu"
               , new { id = (int)e + "-" + Model.ObjectRouting }, htmlAttributes: new object { })
                }

            </td>
        </tr>
    }
</table>