AHP2/AHP2/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AHP2.Models
{
    public class Project
    {
        public int Id { set; get; }
        public string Name { set; get; }

        public DateTime CreateAt { set; get; }
        public DateTime EditAt { set; get; }

        public virtual User User { set; get; }

        [NotMapped]
        public int UserId { set; get; }
    }
}

AHP2/AHP2/Models/ProjectViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AHP2.Models
{
    public class ProjectViewModels
    {
        public IEnumerable<Project> Projects { set; get; }
        public User User { set; get; }
    }
}

AHP2/AHP2/Controllers/ObjectiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AHP2.Models;
using AHP2.Auth;

namespace AHP2.Controllers
{
    [MyAuth]
    public class ObjectiveController : BaseController
    {
        // GET: Objective
        public ActionResult Update(int? id)
        {
            if (id != null)
            {
                var objectiveVM = new ObjectiveViewModels
                {
                    Objective = _ormContext.ObjectivesContext.Where(o => o.Project.Id == (int)id).FirstOrDefault(),
                    PartialMenuViewModels = new PartialMenuViewModels
                    {
                        MenuItem = MenuItem.Objective,
                        ObjectRouting = (int)id
                    }
                };

                return View(objectiveVM);
            }

            return new ViewResult
            {
                ViewName = "~/Views/Errors/Error.cshtml",
            };
        }

        [HttpPost]
        public ActionResult Update(ObjectiveViewModels objectiveVM)
        {

            if(objectiveVM != null)
            {
                    var objective = _ormContext.ObjectivesContext.Include("Project").Where(o => o.Id == objectiveVM.Objective.Id)
                    .FirstOrDefault();
                    objective.Name = objectiveVM.Objective.Name;
                    _ormContext.SaveChanges();
                    return RedirectToAction("Index", "Criterion", new { id = objectiveVM.Objective.Id });
            }
            return new ViewResult
            {
                ViewName = "~/Views/Errors/Error.cshtml",
            };
        }
    }
}

AHP2/AHP2/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AHP2.Models;
using AHP2.Auth;
using AHP2.AhpAlgorithm;

namespace AHP2.Controllers
{
    [MyAuth]
    public class ProjectController : BaseController
    {
        // GET: Project
        public ActionResult Index()
        {
            var user = Session["User"] as User;

            if (user != null)
            {    
                var projects = _ormContext.ProjectsContext.Where(p => p.User.Id == user.Id).ToList();
                ProjectViewModels projectVM = new ProjectViewModels
                {
                    Projects = projects,
                    User = user
                };

                return View(projectVM);
            }

            return new ViewResult
            {
                ViewName = "~/Views/Errors/Error.cshtml",
            };
        }

        public ActionResult Create(int? id)
        {
            if(id != null)
            {
                var project = new Project();
                project.UserId = (int)id;
                return View(project);
            }

            return new ViewResult
            {
                ViewName = "~/Views/Errors/Error.cshtml",
            };
        }

        [HttpPost]
        public ActionResult Create(Project project)
        {
            if(project != null)
            {
                project.User = _ormContext.UsersContext.Where(u => u.Id == project.UserId).FirstOrDefault();
                project.CreateAt = project.EditAt = DateTime.Now.Date;
                _ormContext.ProjectsContext.Add(project);
                _ormContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Delete(int? id)
        {
            if(id != null)
            {
                var project = _ormContext.ProjectsContext.Where(p => p.Id == id).FirstOrDefault();
                _ormContext.ProjectsContext.Remove(project);
                _ormContext.SaveChanges();
                return RedirectToAction("Index");
            }
            HandleErrorInfo handleErrorInfo = new HandleErrorInfo(new Exception("Bad"), "Controller", "Action");
            return new ViewResult
            {
                ViewName = "~/Views/Errors/Error.cshtml",
                ViewData = new ViewDataDictionary(handleErrorInfo)
            };
        }   
    }
}

AHP2/AHP2/Views/Project/Create.cshtml
@model AHP2.Models.Project

@{
    ViewBag.Title = "Create project";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <h2>New project</h2>
    </div>
</div>

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-offset-3 col-md-6 well well-sm">
            <div class="row form-group">
                <div class="col-md-offset-3 col-md-3">
                    @Html.LabelFor(p => p.Name)
                </div>
                <div class="col-md-3">
                    @Html.TextBoxFor(p => p.Name)
                </div>
                @Html.HiddenFor(p => p.UserId, new { @Value = Model.UserId})
            </div>
            <div class="row">
                <input class="btn btn-primary" type="submit" value="Next" />
            </div>
        </div>
    </div>
}

AHP2/AHP2/Views/Project/Index.cshtml
@model AHP2.Models.ProjectViewModels
@{
    ViewBag.Title = "IndexProject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <h2>Projects</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-offset-3 col-md-6 well well-sm">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Project name</th>
                    <th>Date</th>
                </tr>
            </thead>
            @foreach (var p in Model.Projects)
            {
                <tbody>
                    <tr>
                        <td>@Html.ActionLink(p.Name, "Update","Objective", new { id=p.Id }, new { })</td>
                        <td>@Html.ActionLink(p.CreateAt.ToShortDateString(), "Update", "Objective", new { id = p.Id }, new { })</td>
                        <td>@Html.ActionLink("Delete", "Delete", new { id=p.Id}, new { @Class = "delete" })</td>
                    </tr>
                </tbody>
            }
        </table>
            @Html.ActionLink("Create new", "Create", new { id = Model.User.Id }, new { @class="btn btn-primary"})
       
    </div>
</div>